INSERT INTO `categories`(`categoryName`, `categoryDesc`) VALUES ('category 1','Description of Category 1');
INSERT INTO `categories`(`categoryName`, `categoryDesc`) VALUES ('category 2','Description of Category 2');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 1','description 1','1','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 2','description 2','2','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 3','description 3','3','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 4','description 4','4','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 5','description 5','5','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 6','description 6','6','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 7','description 7','7','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 8','description 8','8','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 9','description 9','9','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 10','description 10','10','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 11','description 11','1','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 12','description 12','2','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 13','description 13','3','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 14','description 14','4','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 15','description 15','5','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 16','description 16','6','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 17','description 17','7','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 18','description 18','8','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 19','description 19','9','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 20','description 20','10','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 21','description 21','1','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 22','description 22','2','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 23','description 23','3','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 24','description 24','4','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 25','description 25','5','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 26','description 26','6','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 27','description 27','7','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 28','description 28','8','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 29','description 29','9','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 30','description 30','10','1');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 31','description 31','1','2');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 32','description 32','2','2');
INSERT INTO `inventory`(`name`, `description`, `quantity`, `categoryID`) VALUES ('product 33','description 33','3','2');

INSERT INTO users (username, password,credentialLevel) VALUES ("superadmin", "superpass123", -1);
INSERT INTO users (username, password,credentialLevel) VALUES ("admin", "password", 0);
INSERT INTO users (username, password,credentialLevel) VALUES ("manager", "password", -1);
INSERT INTO users (username, password,credentialLevel) VALUES ("staffuser", "password", -1);
INSERT INTO users (username, password,credentialLevel) VALUES ("viewer", "password", -1);